name: ci-ml-workflow
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          dvc repro
          git fetch --prune
          dvc metrics diff --show-md main > report.md
          echo "## Confusion Matrix" >> report.md
          cml-publish confusion_matrix.png --md >> report.md
          cml-send-comment report.md
